CREATE TABLE "GCG_4720_IssueData"(
 "SCHEDULE" CHAR(6),
 "PART" CHAR(20),
 "ISSUE_AMT" NUMERIC(12,4),
 "FLAG_CLOSED" BIT DEFAULT '0' NOT NULL );

CREATE INDEX "GCG_4720_IDX1" USING 0 ON "GCG_4720_IssueData"("SCHEDULE", "PART");