CREATE TABLE "GCG_4720_ISSUEDETAIL"(
 "SCHEDULE" CHAR(6),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "PART" CHAR(20),
 "ISSUE_AMT" NUMERIC(12,4));

CREATE INDEX "GCG_4720_IDX2" USING 0 ON "GCG_4720_ISSUEDETAIL"("SCHEDULE", "JOB", "SUFFIX", "SEQ", "PART");